name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-staging:
    name: Staging
    uses: ./.github/workflows/deploy-generic.yml
    with:
      environment: Staging
  deploy-prod:
    name: Production
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy-generic.yml
    with:
      environment: Production
