name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-staging:
    name: Staging
    if: github.event.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-generic.yml
    with:
      environment: Staging
  deploy-prod:
    name: Production
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-generic.yml
    with:
      environment: Production
