name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: 'Wrangler (env: ${{ inputs.environment }})'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: exit 0
