name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  deploy:
    name: Wrangler
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    concurrency: ${{ inputs.environment }}
    steps:
      - run: exit ${{ vars.OUTPUT }}
